import Image from "next/image";

const capabilities = [
  { title: "Spread Operations", description: "Map work areas, crews, staging locations and active construction elements along the right-of-way." },
  { title: "Tasks & Progress", description: "Assign and track field work while maintaining a persistent record of meaningful project activity." },
  { title: "Safety", description: "Create and distribute field safety documents, track required acknowledgements and keep outstanding actions visible." },
  { title: "Emergency Response", description: "Broadcast project-wide emergency alerts and associate incidents with their location on the active spread." },
];

function ArrowUpRight() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  return (
    <main>
      <header className="site-header"><a className="brand-logo" href="#top" aria-label="PipeHive home"><Image src="/pipehive-logo.png" alt="PipeHive" width={96} height={96} priority /></a><nav aria-label="Primary navigation"><a href="#product">Product</a><a href="#capabilities">Capabilities</a><a href="#company">Company</a></nav><a className="button button-small" href="#contact">Request a Demo <ArrowUpRight /></a></header>
      <section className="hero" id="top" aria-labelledby="hero-heading"><div className="eyebrow">Field coordination · Pipeline construction</div><h1 id="hero-heading">Field operations software for pipeline construction.</h1><p className="hero-copy">PipeHive gives pipeline construction teams a shared operational view of the right-of-way—connecting field activity, crews, tasks, safety, communication, emergencies, and project progress in one system.</p><a className="button" href="#contact">Request a Demo <ArrowUpRight /></a><p className="hero-note">Developed by PIPEHIVE TECH LTD. in British Columbia, Canada.</p></section>
      <section className="section problem" aria-labelledby="problem-heading"><div className="section-label">The context</div><div className="section-content"><h2 id="problem-heading">Pipeline construction is distributed by nature.</h2><div className="prose"><p>Pipeline projects can stretch across kilometres of active right-of-way, with supervisors, foremen, crews, contractors, inspectors, equipment and materials operating at different locations simultaneously.</p><p>Critical information is often divided between radio traffic, phone calls, messaging, paperwork and separate reporting systems.</p><p>PipeHive is being developed to bring that operational picture together.</p></div></div></section>
      <section className="section product" id="product" aria-labelledby="product-heading"><div className="section-label">The product</div><div className="section-content"><h2 id="product-heading">One shared view of the project.</h2><p className="prose product-intro">PipeHive organizes field operations around a visual representation of the pipeline spread, allowing project teams to see where work is occurring and connect operational information directly to the locations where it matters.</p><div className="product-preview"><Image src="/pipehive-spread-demo.png" alt="PipeHive spread workspace showing construction activity along a pipeline right-of-way" width={3024} height={1964} sizes="(max-width: 700px) calc(100vw - 32px), (max-width: 1200px) 66vw, 800px" /></div></div></section>
      <section className="section capabilities" id="capabilities" aria-labelledby="capabilities-heading"><div className="section-label">Capabilities</div><div className="section-content"><h2 id="capabilities-heading">Built to coordinate the active spread.</h2><div className="capability-grid">{capabilities.map((capability, index) => <article className="capability-card" key={capability.title}><span className="card-number">0{index + 1}</span><h3>{capability.title}</h3><p>{capability.description}</p></article>)}</div></div></section>
      <section className="section field" aria-labelledby="field-heading"><div className="section-label">Built for the field</div><div className="section-content"><h2 id="field-heading">Designed around pipeline construction—not adapted to it.</h2><div className="prose"><p>PipeHive is being developed around the actual structure of pipeline projects: kilometres instead of generic job sites, spreads instead of generic workspaces, and role-specific workflows for supervisors, foremen, crews and specialized contractors.</p><p>The objective is not to replace the people making field decisions. It is to give them a common operational picture from which to make those decisions.</p></div></div></section>
      <section className="stage" aria-labelledby="stage-heading"><div className="stage-inner"><div className="section-label">Current stage</div><h2 id="stage-heading">In development and field validation.</h2><p>PipeHive is currently being developed as a multi-user SaaS platform, with its core project coordination, field task, safety, emergency, progress and communication systems operational.</p><p>PIPEHIVE TECH LTD. is preparing the platform for industry validation and early commercial deployments.</p><a className="button" href="#contact">Request a Demo <ArrowUpRight /></a></div></section>
      <section className="company" id="company" aria-labelledby="company-heading"><div className="company-copy"><div className="section-label">Company</div><h2 id="company-heading">PIPEHIVE TECH LTD.</h2><p>PIPEHIVE TECH LTD. is a British Columbia software company developing operational technology specifically for pipeline and field construction.</p></div><address id="contact"><span>British Columbia, Canada</span><a href="mailto:c.w.larsen@pipehive.net">c.w.larsen@pipehive.net</a></address></section>
      <footer><span>PIPEHIVE TECH LTD. © 2026</span><div><a href="#privacy">Privacy</a><a href="#contact">Contact</a></div></footer>
    </main>
  );
}
